export { default as ExamList } from './ExamList';
export { default as FormCreateExam } from './FormCreateExam';
export { default as ViewDetailExam } from './DetailExam';
export { default as FormEditExam } from './UpdateExam';
export { default as DeleteExam } from './DeleteExam';
export { default as Question } from './Question';
export { default as CheckPractice } from './CheckPractice';
export { default as DoneCreateExam } from './doneCreateExam';
export { default as FormUpdateExam } from './FormUpdateExam';
